from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from ig_client import session_from_env
from ig_markets import pick_best_epic, search_markets


LOGGER = logging.getLogger("trading.ig.discover")


def _norm_symbol(sym: str) -> str:
    sym = sym.strip()
    if not sym:
        return sym
    # Accept both "EURUSD" and "EURUSD=X"
    if "=" in sym:
        return sym
    return f"{sym}=X"


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)sZ %(levelname)s %(name)s - %(message)s")
    p = argparse.ArgumentParser()
    p.add_argument(
        "--symbols",
        required=True,
        help="Comma-separated FX pairs (EURUSD,GBPUSD,...) or training tickers (EURUSD=X,...)",
    )
    p.add_argument(
        "--out",
        default=str(Path(__file__).with_name("ig_epics_generated.json")),
        help="Output JSON path",
    )
    args = p.parse_args()

    symbols = [_norm_symbol(s) for s in args.symbols.split(",") if s.strip()]
    pairs = [s.replace("=X", "").upper() for s in symbols]

    session = session_from_env()
    session.login()
    LOGGER.info("IG login OK (env=%s). Discovering epics for %s symbols...", session.env, len(symbols))

    tickers: dict[str, str | None] = {}
    all_candidates: dict[str, list[dict[str, str | None]]] = {}

    for sym, pair in zip(symbols, pairs, strict=True):
        markets = search_markets(session, pair)
        chosen = pick_best_epic(pair, markets)
        tickers[sym] = chosen
        all_candidates[sym] = [
            {
                "epic": m.epic,
                "instrument_name": m.instrument_name,
                "instrument_type": m.instrument_type,
                "expiry": m.expiry,
            }
            for m in markets[:20]
        ]
        if chosen:
            LOGGER.info("%s -> %s", sym, chosen)
        else:
            LOGGER.warning("%s -> NOT FOUND (check IG instrument availability)", sym)

    out = {
        "notes": [
            "Auto-generated by ig_discover_epics.py. Review before trading.",
            "If a ticker has multiple candidates, pick the right one and update the value.",
        ],
        "tickers": tickers,
        "candidates": all_candidates,
    }
    Path(args.out).write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    LOGGER.info("Wrote mapping: %s", args.out)


if __name__ == "__main__":
    main()

