services:
  - type: web
    name: chatlaya-api
    env: python
    branch: main
    rootDir: INNOVAPLUS/INNOVA
    buildCommand: pip install -r requirements-api.txt
    startCommand: bash bin/prestart.sh && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /healthz
    disk:
      name: models
      mountPath: /var/models
      sizeGB: 20
    envVars:
      - key: MODEL_DIR
        value: /var/models/chatlaya
      - key: MODEL_FILE
        value: chatlaya-smollm-1.7b-q4_k_m.gguf
      - key: HF_FILE_URL
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: N_THREADS
        value: "6"
      - key: N_CTX
        value: "2048"

