services:
  - type: web
    name: chatlaya
    env: python
    buildCommand: pip install -r INNOVAPLUS/INNOVA/requirements.txt
    startCommand: bash INNOVAPLUS/INNOVA/bin/prestart.sh && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_DIR
        value: /var/models/chatlaya
      - key: MODEL_FILE
        value: chatlaya-smollm-1.7b-q4_k_m.gguf
      - key: HF_FILE_URL
        value: https://huggingface.co/<TON_USER>/<REPO>/resolve/main/chatlaya-smollm-1.7b-q4_k_m.gguf
      - key: N_THREADS
        value: "6"
      - key: N_CTX
        value: "2048"
    disk:
      name: chatlaya-model
      mountPath: /var/models
      sizeGB: 20

