from __future__ import annotations


RAW_CONTENT_BASE = "https://raw.githubusercontent.com/Juniorleriche27/koryxa_formation/main/content"


FORMATION_TRACKS = [
    {
        "track_key": "data_analyst",
        "title": "Data Analyst",
        "summary": "Analyse, visualisation, insights et recommandations métier.",
        "description": (
            "Parcours complet d'analyse de données avec Python, depuis les bases jusqu'à un projet "
            "professionnel portfolio-ready."
        ),
        "domain": "data_analysis",
        "difficulty": "beginner_to_operational",
        "estimated_duration": "21h30",
        "skills": ["Python", "SQL", "Pandas", "NumPy", "Visualisation", "EDA"],
        "is_published": True,
    }
]


FORMATION_MODULES = [
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_intro_installation",
        "title": "Introduction & Installation",
        "description": "Mise en place de l'environnement Python, Anaconda et Jupyter Notebook.",
        "order_index": 0,
        "duration": "1h00",
        "notebook_path": None,
        "lesson_count": 5,
        "skills": ["Python", "Jupyter", "Environnement"],
        "is_published": True,
    },
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_python_bases",
        "title": "Les Bases de Python pour la Data",
        "description": "Variables, types, boucles et fonctions expliqués pas à pas.",
        "order_index": 1,
        "duration": "3h00",
        "notebook_path": "MODULE_1_Bases_Python_Data.ipynb",
        "lesson_count": 5,
        "skills": ["Python", "Variables", "Boucles", "Fonctions"],
        "is_published": True,
    },
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_numpy",
        "title": "NumPy : Calcul Numérique",
        "description": "Arrays, opérations vectorisées, indexation et slicing.",
        "order_index": 2,
        "duration": "2h30",
        "notebook_path": "MODULE_2_NumPy_Calcul_Numerique.ipynb",
        "lesson_count": 5,
        "skills": ["NumPy", "Arrays", "Calcul numérique"],
        "is_published": True,
    },
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_pandas",
        "title": "Pandas : Manipulation de Données",
        "description": "DataFrames, lecture CSV, filtres, tris et groupby.",
        "order_index": 3,
        "duration": "3h00",
        "notebook_path": "MODULE_3_Pandas_Manipulation_Donnees.ipynb",
        "lesson_count": 7,
        "skills": ["Pandas", "DataFrames", "CSV", "GroupBy"],
        "is_published": True,
    },
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_cleaning",
        "title": "Nettoyage de Données",
        "description": "Valeurs manquantes, doublons, formats incorrects et outliers.",
        "order_index": 4,
        "duration": "2h30",
        "notebook_path": "MODULE_4_Nettoyage_Donnees.ipynb",
        "lesson_count": 6,
        "skills": ["Cleaning", "Qualité de données", "Outliers"],
        "is_published": True,
    },
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_visualisation",
        "title": "Visualisation de Données",
        "description": "Graphiques professionnels avec Matplotlib et Seaborn.",
        "order_index": 5,
        "duration": "2h30",
        "notebook_path": "MODULE_5_Visualisation_Donnees.ipynb",
        "lesson_count": 5,
        "skills": ["Matplotlib", "Seaborn", "Storytelling visuel"],
        "is_published": True,
    },
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_eda",
        "title": "Analyse Exploratoire (EDA)",
        "description": "Méthodologie complète d'exploration d'un dataset.",
        "order_index": 6,
        "duration": "3h00",
        "notebook_path": "MODULE_6_Analyse_Exploratoire_EDA.ipynb",
        "lesson_count": 5,
        "skills": ["EDA", "Corrélation", "Insights"],
        "is_published": True,
    },
    {
        "track_key": "data_analyst",
        "module_key": "data_analyst_final_project",
        "title": "Projet Final Professionnel",
        "description": "Analyse complète des ventes KORYXA de A à Z pour un premier projet portfolio.",
        "order_index": 7,
        "duration": "4h00",
        "notebook_path": "MODULE_7_Projet_Final_Professionnel.ipynb",
        "lesson_count": 6,
        "skills": ["Projet", "Portfolio", "Business insights"],
        "is_published": True,
    },
]


FORMATION_RESOURCES = [
    {
        "module_key": "data_analyst_intro_installation",
        "title": "Support d'introduction et installation",
        "url": f"{RAW_CONTENT_BASE}/MODULE_0_Introduction_Installation.docx",
        "resource_type": "document",
        "description": "Guide d'installation et de démarrage du parcours Data Analyst.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_python_bases",
        "title": "Notebook Python pour la Data",
        "url": f"{RAW_CONTENT_BASE}/MODULE_1_Bases_Python_Data.ipynb",
        "resource_type": "notebook",
        "description": "Notebook complet sur les bases de Python appliquées à la data.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_numpy",
        "title": "Notebook NumPy",
        "url": f"{RAW_CONTENT_BASE}/MODULE_2_NumPy_Calcul_Numerique.ipynb",
        "resource_type": "notebook",
        "description": "Notebook complet sur le calcul numérique avec NumPy.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_pandas",
        "title": "Notebook Pandas",
        "url": f"{RAW_CONTENT_BASE}/MODULE_3_Pandas_Manipulation_Donnees.ipynb",
        "resource_type": "notebook",
        "description": "Notebook complet de manipulation de données avec Pandas.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_cleaning",
        "title": "Notebook Nettoyage de Données",
        "url": f"{RAW_CONTENT_BASE}/MODULE_4_Nettoyage_Donnees.ipynb",
        "resource_type": "notebook",
        "description": "Notebook complet de nettoyage et préparation des données.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_visualisation",
        "title": "Notebook Visualisation",
        "url": f"{RAW_CONTENT_BASE}/MODULE_5_Visualisation_Donnees.ipynb",
        "resource_type": "notebook",
        "description": "Notebook complet de visualisation avec Matplotlib et Seaborn.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_eda",
        "title": "Notebook EDA",
        "url": f"{RAW_CONTENT_BASE}/MODULE_6_Analyse_Exploratoire_EDA.ipynb",
        "resource_type": "notebook",
        "description": "Notebook d'analyse exploratoire de données.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_final_project",
        "title": "Notebook Projet Final",
        "url": f"{RAW_CONTENT_BASE}/MODULE_7_Projet_Final_Professionnel.ipynb",
        "resource_type": "notebook",
        "description": "Notebook du projet final portfolio-ready.",
        "order_index": 1,
    },
    {
        "module_key": "data_analyst_final_project",
        "title": "Dataset ventes KORYXA",
        "url": f"{RAW_CONTENT_BASE}/ventes_koryxa.csv",
        "resource_type": "dataset",
        "description": "Jeu de données principal pour le projet final.",
        "order_index": 2,
    },
    {
        "module_key": "data_analyst_final_project",
        "title": "Dataset ventes KORYXA propre",
        "url": f"{RAW_CONTENT_BASE}/ventes_koryxa_propre.csv",
        "resource_type": "dataset",
        "description": "Version nettoyée du dataset de ventes.",
        "order_index": 3,
    },
]
