begin;

create extension if not exists pgcrypto;
create extension if not exists vector;

create schema if not exists app;

create or replace function app.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function app.current_user_id()
returns uuid
language sql
stable
as $$
  select auth.uid();
$$;

create table if not exists app.auth_users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password_hash text not null,
  first_name text not null,
  last_name text not null,
  country text null,
  account_type text null check (account_type in ('learner', 'company', 'organization')),
  workspace_role text null check (workspace_role in ('demandeur', 'prestataire')),
  plan text not null default 'free' check (plan in ('free', 'pro', 'team')),
  roles jsonb not null default '["user"]'::jsonb,
  password_updated_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists auth_users_email_lower_key on app.auth_users ((lower(email)));

drop trigger if exists trg_auth_users_updated_at on app.auth_users;
create trigger trg_auth_users_updated_at
before update on app.auth_users
for each row execute function app.set_updated_at();

create table if not exists public.enterprise_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text not null,
  role text not null,
  team_size text not null,
  need text not null,
  message text not null default '',
  source_page text not null default '/entreprise',
  source_ts timestamptz null,
  status text not null default 'new' check (status in ('new', 'contacted', 'qualified', 'lost', 'won')),
  assigned_to text null,
  notes text null,
  contacted_at timestamptz null,
  client_ip text null,
  user_agent text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists enterprise_leads_created_at_idx on public.enterprise_leads (created_at desc);
create index if not exists enterprise_leads_status_created_at_idx on public.enterprise_leads (status, created_at desc);
create index if not exists enterprise_leads_email_lower_idx on public.enterprise_leads ((lower(email)));

drop trigger if exists trg_enterprise_leads_updated_at on public.enterprise_leads;
create trigger trg_enterprise_leads_updated_at
before update on public.enterprise_leads
for each row execute function app.set_updated_at();

create table if not exists app.sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references app.auth_users(id) on delete cascade,
  token_hash text not null unique,
  issued_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null,
  revoked boolean not null default false,
  ip text null,
  ua text null,
  last_seen_at timestamptz not null default timezone('utc', now())
);

create index if not exists sessions_user_revoked_idx on app.sessions (user_id, revoked, expires_at desc);

create table if not exists app.password_reset_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references app.auth_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists password_reset_tokens_user_used_idx on app.password_reset_tokens (user_id, used, created_at desc);

create table if not exists app.login_otps (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  code_hash text not null,
  intent text not null default 'login',
  expires_at timestamptz not null,
  consumed_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists login_otps_email_created_idx on app.login_otps (lower(email), created_at desc);

create table if not exists app.trajectory_flows (
  id uuid primary key default gen_random_uuid(),
  guest_id text null,
  user_id uuid null references app.auth_users(id) on delete set null,
  status text not null default 'onboarded',
  onboarding jsonb not null default '{}'::jsonb,
  diagnostic jsonb null,
  progress_plan jsonb null,
  final_recommendation jsonb null,
  submitted_to_team boolean not null default false,
  proofs jsonb not null default '[]'::jsonb,
  verified_profile jsonb null,
  opportunity_targets jsonb not null default '[]'::jsonb,
  enrolled_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists trajectory_flows_guest_updated_idx on app.trajectory_flows (guest_id, updated_at desc);
create index if not exists trajectory_flows_user_updated_idx on app.trajectory_flows (user_id, updated_at desc);

drop trigger if exists trg_trajectory_flows_updated_at on app.trajectory_flows;
create trigger trg_trajectory_flows_updated_at
before update on app.trajectory_flows
for each row execute function app.set_updated_at();

create table if not exists app.trajectory_task_bindings (
  id uuid primary key default gen_random_uuid(),
  flow_id uuid not null references app.trajectory_flows(id) on delete cascade,
  user_id uuid not null references app.auth_users(id) on delete cascade,
  context_id text not null,
  koryxa_stage_key text not null,
  koryxa_task_key text not null,
  proof_required boolean not null default false,
  feature_gate text null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (flow_id, user_id, koryxa_task_key)
);

create index if not exists trajectory_task_bindings_user_context_idx on app.trajectory_task_bindings (user_id, context_id, updated_at desc);

drop trigger if exists trg_trajectory_task_bindings_updated_at on app.trajectory_task_bindings;
create trigger trg_trajectory_task_bindings_updated_at
before update on app.trajectory_task_bindings
for each row execute function app.set_updated_at();

create table if not exists app.training_diagnostic_leads (
  flow_id uuid primary key references app.trajectory_flows(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text not null,
  whatsapp_country_code text not null,
  whatsapp_number text not null,
  submitted_at timestamptz not null default timezone('utc', now())
);

create table if not exists app.enterprise_needs (
  id uuid primary key default gen_random_uuid(),
  guest_id text null,
  user_id uuid null references app.auth_users(id) on delete set null,
  title text not null,
  company_name text not null,
  primary_goal text not null,
  need_type text not null,
  expected_result text not null,
  urgency text not null,
  treatment_preference text not null,
  recommended_treatment_mode text not null,
  team_context text not null,
  support_preference text not null,
  short_brief text null,
  status text not null,
  qualification_score integer not null default 0,
  clarity_level text not null,
  structured_summary text not null,
  next_recommended_action text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists enterprise_needs_guest_created_idx on app.enterprise_needs (guest_id, created_at desc);
create index if not exists enterprise_needs_user_created_idx on app.enterprise_needs (user_id, created_at desc);

drop trigger if exists trg_enterprise_needs_updated_at on app.enterprise_needs;
create trigger trg_enterprise_needs_updated_at
before update on app.enterprise_needs
for each row execute function app.set_updated_at();

create table if not exists app.enterprise_missions (
  id uuid primary key default gen_random_uuid(),
  need_id uuid not null unique references app.enterprise_needs(id) on delete cascade,
  guest_id text null,
  user_id uuid null references app.auth_users(id) on delete set null,
  title text not null,
  summary text not null,
  deliverable text not null,
  execution_mode text not null,
  status text not null,
  steps jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists trg_enterprise_missions_updated_at on app.enterprise_missions;
create trigger trg_enterprise_missions_updated_at
before update on app.enterprise_missions
for each row execute function app.set_updated_at();

create table if not exists app.enterprise_opportunities (
  id uuid primary key default gen_random_uuid(),
  need_id uuid not null unique references app.enterprise_needs(id) on delete cascade,
  mission_id uuid not null references app.enterprise_missions(id) on delete cascade,
  user_id uuid null references app.auth_users(id) on delete set null,
  type text not null,
  title text not null,
  summary text not null,
  status text not null,
  highlights jsonb not null default '[]'::jsonb,
  published_at timestamptz null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists enterprise_opportunities_status_published_idx on app.enterprise_opportunities (status, published_at desc);

drop trigger if exists trg_enterprise_opportunities_updated_at on app.enterprise_opportunities;
create trigger trg_enterprise_opportunities_updated_at
before update on app.enterprise_opportunities
for each row execute function app.set_updated_at();

create table if not exists app.enterprise_task_bindings (
  id uuid primary key default gen_random_uuid(),
  need_id uuid not null references app.enterprise_needs(id) on delete cascade,
  user_id uuid not null references app.auth_users(id) on delete cascade,
  context_id text not null,
  step_key text not null,
  step_title text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (need_id, user_id, step_key)
);

create index if not exists enterprise_task_bindings_user_context_idx on app.enterprise_task_bindings (user_id, context_id, updated_at desc);

drop trigger if exists trg_enterprise_task_bindings_updated_at on app.enterprise_task_bindings;
create trigger trg_enterprise_task_bindings_updated_at
before update on app.enterprise_task_bindings
for each row execute function app.set_updated_at();

create table if not exists app.public_products (
  slug text primary key,
  name text not null,
  href text not null,
  eyebrow text not null,
  summary text not null,
  bullets jsonb not null default '[]'::jsonb,
  cta text not null,
  visible boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists public_products_visible_name_idx on app.public_products (visible, name);

drop trigger if exists trg_public_products_updated_at on app.public_products;
create trigger trg_public_products_updated_at
before update on app.public_products
for each row execute function app.set_updated_at();

create table if not exists app.rag_documents (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  source_file text not null,
  source_path text null,
  mime_type text null,
  checksum text null,
  chunk_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists rag_documents_slug_idx on app.rag_documents (slug);
create index if not exists rag_documents_source_file_idx on app.rag_documents (source_file);

drop trigger if exists trg_rag_documents_updated_at on app.rag_documents;
create trigger trg_rag_documents_updated_at
before update on app.rag_documents
for each row execute function app.set_updated_at();

create table if not exists app.rag_chunks (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references app.rag_documents(id) on delete cascade,
  chunk_index integer not null,
  title text not null,
  source_file text not null,
  content text not null,
  content_tsv tsvector generated always as (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, ''))) stored,
  embedding vector(1024) null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (document_id, chunk_index)
);

alter table app.rag_chunks
add column if not exists embedding vector(1024);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'app'
      and table_name = 'rag_chunks'
      and column_name = 'embedding'
  ) and not exists (
    select 1
    from app.rag_chunks
    where embedding is not null
  ) then
    alter table app.rag_chunks
    alter column embedding type vector(1024);
  end if;
end;
$$;

create index if not exists rag_chunks_document_chunk_idx on app.rag_chunks (document_id, chunk_index);
create index if not exists rag_chunks_source_file_idx on app.rag_chunks (source_file);
create index if not exists rag_chunks_content_tsv_idx on app.rag_chunks using gin (content_tsv);
create index if not exists rag_chunks_embedding_hnsw_idx on app.rag_chunks using hnsw (embedding vector_cosine_ops);

create or replace function app.match_rag_chunks(
  query_embedding vector(1024),
  match_count integer default 5,
  filter_corpus text default null
)
returns table (
  chunk_id uuid,
  document_id uuid,
  chunk_index integer,
  title text,
  source_file text,
  content text,
  metadata jsonb,
  score double precision
)
language sql
stable
as $$
  select
    c.id as chunk_id,
    c.document_id,
    c.chunk_index,
    c.title,
    c.source_file,
    c.content,
    c.metadata,
    1 - (c.embedding <=> query_embedding) as score
  from app.rag_chunks c
  join app.rag_documents d on d.id = c.document_id
  where c.embedding is not null
    and (
      filter_corpus is null
      or coalesce(d.metadata->>'corpus', '') = filter_corpus
    )
  order by c.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;

commit;
